"""Initial schema with all tables

Revision ID: d8f8f367019a
Revises: 
Create Date: 2026-10-01 21:20:12.475239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f8f367019a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url_or_path', sa.String(length=1024), nullable=False),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_detail', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('repo_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_repo_id'), 'chat_sessions', ['repo_id'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('embedding_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_tracking_id'), 'cost_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_cost_tracking_repo_id'), 'cost_tracking', ['repo_id'], unique=False)
    op.create_table('folder_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('folder_path', sa.String(length=1024), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_folder_repo_path', 'folder_summaries', ['repo_id', 'folder_path'], unique=True)
    op.create_index(op.f('ix_folder_summaries_id'), 'folder_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_folder_summaries_repo_id'), 'folder_summaries', ['repo_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_repo_id'), 'jobs', ['repo_id'], unique=False)
    op.create_table('repo_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_versions_id'), 'repo_versions', ['id'], unique=False)
    op.create_index(op.f('ix_repo_versions_repo_id'), 'repo_versions', ['repo_id'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('tour_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_index(op.f('ix_tours_repo_id'), 'tours', ['repo_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('is_entrypoint', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['repo_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('ix_files_repo_id'), 'files', ['repo_id'], unique=False)
    op.create_index('ix_files_repo_path', 'files', ['repo_id', 'path'], unique=True)
    op.create_table('tour_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_steps_id'), 'tour_steps', ['id'], unique=False)
    op.create_index(op.f('ix_tour_steps_tour_id'), 'tour_steps', ['tour_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('parent_symbol_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qualified_name', sa.String(length=512), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('docstring', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_file_id'), 'symbols', ['file_id'], unique=False)
    op.create_index(op.f('ix_symbols_id'), 'symbols', ['id'], unique=False)
    op.create_index('ix_symbols_kind', 'symbols', ['repo_id', 'kind'], unique=False)
    op.create_index('ix_symbols_lookup', 'symbols', ['repo_id', 'name'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=False)
    op.create_index(op.f('ix_symbols_qualified_name'), 'symbols', ['qualified_name'], unique=False)
    op.create_index(op.f('ix_symbols_repo_id'), 'symbols', ['repo_id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('header', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunk_embeddings_content_hash'), 'chunk_embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_file_id'), 'chunk_embeddings', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_id'), 'chunk_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_repo_id'), 'chunk_embeddings', ['repo_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_symbol_id'), 'chunk_embeddings', ['symbol_id'], unique=False)
    op.create_index('ix_chunks_content_hash', 'chunk_embeddings', ['content_hash'], unique=False)
    op.create_index('ix_chunks_repo_file', 'chunk_embeddings', ['repo_id', 'file_path'], unique=False)
    op.create_index('ix_chunks_symbol', 'chunk_embeddings', ['repo_id', 'symbol_name'], unique=False)
    op.create_table('symbol_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('src_symbol_id', sa.Integer(), nullable=True),
    sa.Column('dst_symbol_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(length=1024), nullable=False),
    sa.Column('source_symbol', sa.String(length=255), nullable=False),
    sa.Column('target_file', sa.String(length=1024), nullable=True),
    sa.Column('target_symbol', sa.String(length=255), nullable=False),
    sa.Column('dst_name', sa.String(length=255), nullable=True),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dst_symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_symbol_id'], ['symbols.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_source', 'symbol_edges', ['repo_id', 'source_symbol'], unique=False)
    op.create_index('ix_edge_target', 'symbol_edges', ['repo_id', 'target_symbol'], unique=False)
    op.create_index('ix_edge_type', 'symbol_edges', ['repo_id', 'edge_type'], unique=False)
    op.create_index(op.f('ix_symbol_edges_id'), 'symbol_edges', ['id'], unique=False)
    op.create_index(op.f('ix_symbol_edges_repo_id'), 'symbol_edges', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_edges_repo_id'), table_name='symbol_edges')
    op.drop_index(op.f('ix_symbol_edges_id'), table_name='symbol_edges')
    op.drop_index('ix_edge_type', table_name='symbol_edges')
    op.drop_index('ix_edge_target', table_name='symbol_edges')
    op.drop_index('ix_edge_source', table_name='symbol_edges')
    op.drop_table('symbol_edges')
    op.drop_index('ix_chunks_symbol', table_name='chunk_embeddings')
    op.drop_index('ix_chunks_repo_file', table_name='chunk_embeddings')
    op.drop_index('ix_chunks_content_hash', table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_symbol_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_repo_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_file_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_content_hash'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index(op.f('ix_symbols_repo_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_qualified_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index('ix_symbols_lookup', table_name='symbols')
    op.drop_index('ix_symbols_kind', table_name='symbols')
    op.drop_index(op.f('ix_symbols_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_file_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_tour_steps_tour_id'), table_name='tour_steps')
    op.drop_index(op.f('ix_tour_steps_id'), table_name='tour_steps')
    op.drop_table('tour_steps')
    op.drop_index('ix_files_repo_path', table_name='files')
    op.drop_index(op.f('ix_files_repo_id'), table_name='files')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_tours_repo_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_repo_versions_repo_id'), table_name='repo_versions')
    op.drop_index(op.f('ix_repo_versions_id'), table_name='repo_versions')
    op.drop_table('repo_versions')
    op.drop_index(op.f('ix_jobs_repo_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_folder_summaries_repo_id'), table_name='folder_summaries')
    op.drop_index(op.f('ix_folder_summaries_id'), table_name='folder_summaries')
    op.drop_index('ix_folder_repo_path', table_name='folder_summaries')
    op.drop_table('folder_summaries')
    op.drop_index(op.f('ix_cost_tracking_repo_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_id'), table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_index(op.f('ix_chat_sessions_repo_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
